-- require("astrotheme").setup({
--     highlights = {
--         global = {
--             ["@lsp.type.variable"] = { link = "@variable.builtin"}
--         },
--     },
-- })
-- vim.cmd.colorscheme  'astrodark'
-- vim.cmd.colorscheme  'catppuccin-macchiato'
-- vim.cmd.colorscheme  'tokyonight-storm'
vim.cmd.colorscheme("onedark_vivid")
